service: hwv1

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-southeast-1
  memorySize: 256

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/{any+}
          method: ANY
          cors: true    

package:
  excludeDevDependencies: true
  individually: false
  exclude:
    - .serverlss
    - .warmup
    - node_modules/**

#plugins:
#  - serverless-aws-alias