service: hwv1

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  memorySize: 256
  aliasStage:
    loggingLevel: "ERROR"
    dataTraceEnabled: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello/get
          method: get
          cors: true    

#plugins:
#  - serverless-aws-alias