service: sls-express-ex

frameworkVersion: '3'

provider:
  name: aws
  region: us-west-2
  runtime: nodejs14.x
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
