service: helloworld-layer

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  memorySize: 256
  environment:
    DB_CONSTRING: ${self:custom.env.DB_CONSTRING}
    REDIS_HOST: ${self:custom.env.REDIS_HOST}
    REDIS_PORT: ${self:custom.env.REDIS_PORT}
    REDIS_PW: ${self:custom.env.REDIS_PW}

layers:
  libs:
    path: layer
    name: layerLibs
    compatibleRuntimes:
      - nodejs14.x

custom:
  env: ${file(./env/${opt:stage,'local'}.json)}
  prune:
    automatic: true
    number: 3
  warmup:
    a5Warmer:
      enabled: false
      events:
        - schedule: cron(0/5 15-16 ? * MON *)
      concurrency: 1
    b5Warmer:
      enabled: true
      events:
        - schedule: cron(0/5 05-06 ? * MON *)
  splitStacks:
    nestedStackCount: 10
    perFunction: false
    perType: false
    perGroupFunction: false


package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - .serverlss
    - .warmup
    - layer/**
    - node_modules/**
    - functions/fonts/**

functions: ${file(${opt:config-file}):functions}


plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-warmup
  - serverless-plugin-split-stacks
  

# sls deploy --stage dev --profile sls -v --force --config-file slsfunctions.js  
# aws cloudformation delete-stack --stack-name helloworld-layer-dev