service: helloworld

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  memorySize: 256
  environment:
    DB_CONSTRING: ${self:custom.env.DB_CONSTRING}
    REDIS_HOST: ${self:custom.env.REDIS_HOST}
    REDIS_PORT: ${self:custom.env.REDIS_PORT}
    REDIS_PW: ${self:custom.env.REDIS_PW}
    #NODE_PATH: "./:/opt/node_modules"  

custom:
  env: ${file(./env/${opt:stage,'local'}.json)}
  prune:
    automatic: true
    number: 3
  warmup:
    a5Warmer:
      enabled: true
      events:
        - schedule: cron(0/5 15-16 ? * MON *)
        - schedule: cron(0/5 15-16 ? * TUE *)
#        - schedule: cron(0/5 15-16 ? * WEN *)
#        - schedule: cron(0/5 15-16 ? * THR *)
#        - schedule: cron(0/5 15-16 ? * FRI *)
#        - schedule: cron(0/5 15-16 ? * SAT *)
#        - schedule: cron(0/5 15-16 ? * SUN *)
      concurrency: 1
    b5Warmer:
      enabled: true
      events:
        - schedule: cron(0/5 05-06 ? * MON *)
#        - schedule: cron(0/5 05-06 ? * TUE *)
#        - schedule: cron(0/5 05-06 ? * WEN *)
#        - schedule: cron(0/5 05-06 ? * THR *)
#        - schedule: cron(0/5 05-06 ? * FRI *)
#        - schedule: cron(0/5 05-06 ? * SAT *)
#        - schedule: cron(0/5 05-06 ? * SUN *)
#      concurrency: 1
#    testWarmer:
#      enabled: false
  serverless-layers:
    dependenciesPath: package.json
    compatibleRuntimes: [nodejs14.x]
    layersDeploymentBucket: "helloworld-layer-bucket"
  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: false

package:
  excludeDevDependencies: true
  individually: false
  exclude:
#    - node_modules/**
    - .warmup/**
#  include:

functions: ${file(${opt:config-file}):functions}

plugins:
  - serverless-offline
  - serverless-prune-plugin
#  - serverless-layers
  - serverless-plugin-warmup
#  - serverless-plugin-include-dependencies
  - serverless-plugin-split-stacks
  